[
	{
	"id":"1",
	"firstName":"Michel",
	"lastName":"Clark",
	"fatherName":"Mitchel",
	"motherName":"Rihana",
	"dob":"2000",
	"class":"10",
	"seciton":"A",
	"grade":"B",
	"percent":"57"
	},
	{
	"id":"2",
	"firstName":"Michel",
	"lastName":"Bewan",
	"fatherName":"Adam",
	"motherName":"Celina",
	"dob":"2001",
	"class":"10",
	"seciton":"A",
	"grade":"A",
	"percent":"80"
	},

	{
	"id":"3",
	"firstName":"Mitchel",
	"lastName":"Johnson",
	"fatherName":"Mular",
	"motherName":"Welina",
	"dob":"2000",
	"class":"10",
	"seciton":"A",
	"grade":"A",
	"percent":"70"
	},

	{
	"id":"4",
	"firstName":"Mitchel",
	"lastName":"Robinson",
	"fatherName":"Robina",
	"motherName":"Alestar",
	"dob":"2001",
	"class":"10",
	"seciton":"B",
	"grade":"C",
	"percent":"48"
	},

	{
	"id":"5",
	"firstName":"Michel",
	"lastName":"Flower",
	"fatherName":"Rezina",
	"motherName":"Jonemone",
	"dob":"2000",
	"class":"10",
	"seciton":"A",
	"grade":"A",
	"percent":"75"
	},

	{
	"id":"6",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},

	{
	"id":"7",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},

	{
	"id":"8",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},

	{
	"id":"9",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},

	{
	"id":"10",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},

	{
	"id":"11",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},
	{
	"id":"12",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},
	{
	"id":"13",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},
	{
	"id":"14",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	},
	{
	"id":"15",
	"firstName":"",
	"lastName":"",
	"fatherName":"",
	"motherName":"",
	"dob":"",
	"class":"",
	"seciton":"",
	"grade":"",
	"percent":""
	}
]